- hosts: linux
  become: yes
  tasks:
    - name: apt update && upgrade
      apt:
        update_cache: yes
        upgrade: yes

    - name: apt dist upgrade && autoremove
      apt:
        upgrade: dist
        autoremove: true
