- hosts: srv-ansibletest
  become: true
  vars:
    default_container_name: alpinetest
    default_container_image: alpine
    default_container_command: bin/sh

  tasks:
    - name: installation des dépendances/outils en plus
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - gnupg
        state: latest
        update_cache: true

    - name: créer apt/keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

#################
#
# NE PLUS TOUCHER
#
#################
#
    - name: On récupère la clé gpg de Docker
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: On ajoute le repo docker dans la source list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
#
#################
#
# NE PLUS TOUCHER
#
#################

    - name: apt update
      apt:
        update_cache: true


    - name: Installation de plusieurs options de Docker
      apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry

    - name: Pull de l'image voulue
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Création du conteneur à partir de l'image
      community.docker.docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
